# Generated by Django 5.0.3 on 2024-03-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientname', models.CharField(max_length=150)),
                ('doctorname', models.CharField(max_length=150)),
                ('appointmentdate', models.CharField(max_length=150)),
                ('symptoms', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientname', models.CharField(max_length=150)),
                ('dob', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('contactnum', models.CharField(max_length=100)),
                ('doctorname', models.CharField(blank=True, max_length=150, null=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('password', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
