# Generated by Django 5.0.3 on 2024-03-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_patient_age_remove_patient_contactnum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='password1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
