# Generated by Django 5.0.3 on 2024-04-03 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='doctorname',
        ),
    ]
